name: Report an issue with Solcast PV Solar Integration
description: Report an issue with Solcast PV Solar Home Assistant Integration.
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs only!
        
        Do not just write 'it does not work, vX.X.X, HA, X.X.X'

        If you do, and don't provide additional background, such as whether or not this is a new install,
        or an upgrade, and if so, from what version, you may find that your issue is deleted without comment.
        
        Particularly if your issue is triaged first by the repo owner who is in a grumpy mood
        because he is suffering from chronic migraines.

        Help us help you be providing more information, not less.
        
        If not enough information is supplied the you may not get the support you hope for. 

        If you have a feature or enhancement request, please use the feature request Issue Type.
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Describe the issue you are experiencing here. What ere you trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Solcast Integration has the issue?
      placeholder: vX.X.XX
      description: >
        Can be found in: Settings ⇒ Devices & Services ⇒ Solcast Solar ⇒ top left box Service info ⇒ Version.

  - type: input
    id: haversion
    validations:
      required: true
    attributes:
      label: What version of Home Assistant are you using?
      placeholder: core-
      description: >
        If known, otherwise leave blank.

  - type: markdown
    attributes:
      value: |
        # Details
  - type: textarea
    attributes:
      label: Diagnostics information
      placeholder: "drag-and-drop the diagnostics data file here (do not copy-and-paste the content)"
      description: >-
        This integrations provide the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#debug-logs-and-diagnostics).

        **It would really help if you could download the diagnostics data,
        and <ins>drag-and-drop that file into the textbox below.</ins>**

        It generally allows pinpointing defects and thus resolving issues faster.

  - type: textarea
    id: loginfo
    validations:
      required: true
    attributes:
      label: Logs debug/info/error output
      placeholder: "paste debug logs below"
      description: >- 
        Debug info, error message, or stack traces.
        
        Logs are essential for debugging issues, and **must be supplied** to debug issues.
        
        Please please ensure that you have enabled debug logs as described [here](https://github.com/BJReplay/ha-solcast-solar/discussions/38#discussioncomment-9792389) and paste the debug logs below

        To inspect and collect debug logs examine `/config/home-assistant.log` using File Editor or Visual Studio Code Server.

        If you are using docker, it sometimes can be easier to gather logs using `docker compose logs -n 500 -f homeassistant` or similar
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
